dev-python/numpy: prevent LTO from being used
The build fails:

```
../numpy-1.26.3/numpy/core/src/multiarray/experimental_public_dtype_api.c:389:1: error: type of ‘PyUFunc_AddLoopFromSpec’ does not match original declaration [-Werror=lto-type-mismatch]
```

This is interesting since it implies the failure is purely in
experimental code rework, which it would be nice to not have regressions
in...

Closes: https://bugs.gentoo.org/     922457
Signed-off-by: Eli Schwartz <eschwartz93@gmail.com>